name: Firestore rules deploy

on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        - uses: actions/checkout@v2
        
        - name: Deploy Firestore rules to Firebase
          uses: w9jds/firebase-action@master
          with:
            args: deploy --only firestore:rules
          env:            
            FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}